title: 'Aircrft '
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
favicon: images/favicon.ico
logo_dark: images/13F2CA89-4087-473C-BBD2-54F5252724BB.png
logo_light: images/034DF580-BA69-4736-BE7F-CA760A910A9D.png
hamburger_background_image: images/C3887F39-12FB-4B8B-A21C-ACC604A3F332.jpeg
bg_image_primary: /images/header.jpg
bg_image_primary_opacity: 60
bg_image_secondary: /images/leaf-light-grey.svg
bg_image_product: /images/leaf.svg
snipcart_api_key: MDA5MzhhMzctM2NhNS00MzJiLTk2OTctYWVkNzZhODg0ZjNiNjM3NTI3MzAyMDQ1NzE0NzA4
footer_text: Copyright 2021 Planty Inc. All rights reserved.
palette: green
main_menu:
  - title: Store
    url: /store
    style: link
  - title: About
    url: /about
    style: link
  - title: FAQ
    url: /faq
    style: link
  - title: lorem-ipsum
    url: lorem-ipsum
    style: primary
    arrow: false
    type: action
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
